# Generated by Django 4.2.4 on 2023-08-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('ORDER RECEVIED', 'ORDER RECEVIED'), ('ORDER ON THE WAY', 'ORDER ON THE WAY'), ('ORDER PROCESSED', 'ORDER PROCESSED'), ('ORDER COMPLETED', 'ORDER COMPLETED'), ('ORDER CANCELLED', 'ORDER CANCELLED')], max_length=45),
        ),
    ]
