# Generated by Django 4.2.4 on 2023-08-14 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0003_rename_ordered_by_order_name_alter_cart_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='admins')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomapp.cart'),
        ),
    ]
