# Generated by Django 4.2.4 on 2023-08-17 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0009_alter_customer_user_productimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Productimage',
        ),
    ]
