# Generated by Django 4.2.4 on 2023-08-18 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0012_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
    ]
