# Generated by Django 4.2.4 on 2023-08-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0016_order_payment_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_completed',
            new_name='completed_payment',
        ),
        migrations.AddField(
            model_name='order',
            name='paymentmethod',
            field=models.CharField(choices=[('CASH ON DELIEVERY', 'CASH ON DELIVERY'), ('RAZORPAY', 'RAZORPAY')], default='cash on delivery', max_length=20),
        ),
    ]
